enum ProductCategory {
  electronics, books, clothing, furniture,
  kitchenware, sports, stationery, other,
}

enum ProductStatus { available, sold, reserved }

class ProductModel {
  final String id;
  final String title;
  final String description;
  final ProductCategory category;
  final double price;
  final List<String> imageUrls;
  final String sellerId;
  final String sellerName;
  final String sellerHostel;
  final String sellerPhone;
  final ProductStatus status;
  final DateTime createdAt;
  bool isWishlisted;

  ProductModel({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.price,
    required this.imageUrls,
    required this.sellerId,
    required this.sellerName,
    required this.sellerHostel,
    required this.sellerPhone,
    this.status = ProductStatus.available,
    required this.createdAt,
    this.isWishlisted = false,
  });

  String get categoryLabel {
    const labels = {
      ProductCategory.electronics: 'Electronics',
      ProductCategory.books:       'Books',
      ProductCategory.clothing:    'Clothing',
      ProductCategory.furniture:   'Furniture',
      ProductCategory.kitchenware: 'Kitchenware',
      ProductCategory.sports:      'Sports',
      ProductCategory.stationery:  'Stationery',
      ProductCategory.other:       'Other',
    };
    return labels[category] ?? 'Other';
  }

  String get statusLabel {
    const labels = {
      ProductStatus.available: 'Available',
      ProductStatus.sold:      'Sold',
      ProductStatus.reserved:  'Reserved',
    };
    return labels[status] ?? 'Available';
  }

  ProductModel copyWith({
    String? id, String? title, String? description,
    ProductCategory? category, double? price, List<String>? imageUrls,
    String? sellerId, String? sellerName, String? sellerHostel,
    String? sellerPhone, ProductStatus? status, DateTime? createdAt,
    bool? isWishlisted,
  }) {
    return ProductModel(
      id:           id           ?? this.id,
      title:        title        ?? this.title,
      description:  description  ?? this.description,
      category:     category     ?? this.category,
      price:        price        ?? this.price,
      imageUrls:    imageUrls    ?? this.imageUrls,
      sellerId:     sellerId     ?? this.sellerId,
      sellerName:   sellerName   ?? this.sellerName,
      sellerHostel: sellerHostel ?? this.sellerHostel,
      sellerPhone:  sellerPhone  ?? this.sellerPhone,
      status:       status       ?? this.status,
      createdAt:    createdAt    ?? this.createdAt,
      isWishlisted: isWishlisted ?? this.isWishlisted,
    );
  }

  /// Supabase INSERT payload (snake_case, no id — generated by DB)
  Map<String, dynamic> toSupabase() {
    return {
      'title':         title,
      'description':   description,
      'category':      category.name,
      'price':         price,
      'image_urls':    imageUrls,
      'seller_id':     sellerId,
      'seller_name':   sellerName,
      'seller_hostel': sellerHostel,
      'seller_phone':  sellerPhone,
      'status':        status.name,
    };
  }

  /// Build from Supabase products row
  factory ProductModel.fromSupabase(Map<String, dynamic> row) {
    return ProductModel(
      id:           row['id']           as String,
      title:        (row['title']        as String?) ?? '',
      description:  (row['description']  as String?) ?? '',
      category: ProductCategory.values.firstWhere(
        (c) => c.name == (row['category'] ?? 'other'),
        orElse: () => ProductCategory.other,
      ),
      price:        ((row['price'] ?? 0) as num).toDouble(),
      imageUrls:    List<String>.from((row['image_urls'] as List?) ?? []),
      sellerId:     row['seller_id']    as String,
      sellerName:   (row['seller_name']   as String?) ?? '',
      sellerHostel: (row['seller_hostel'] as String?) ?? '',
      sellerPhone:  (row['seller_phone']  as String?) ?? '',
      status: ProductStatus.values.firstWhere(
        (s) => s.name == (row['status'] ?? 'available'),
        orElse: () => ProductStatus.available,
      ),
      createdAt: DateTime.parse(
        (row['created_at'] as String?) ?? DateTime.now().toIso8601String(),
      ),
    );
  }

  // Legacy map helpers
  Map<String, dynamic> toMap() => {
    'id':           id,
    'title':        title,
    'description':  description,
    'category':     category.name,
    'price':        price,
    'imageUrls':    imageUrls,
    'sellerId':     sellerId,
    'sellerName':   sellerName,
    'sellerHostel': sellerHostel,
    'sellerPhone':  sellerPhone,
    'status':       status.name,
    'createdAt':    createdAt.toIso8601String(),
  };

  factory ProductModel.fromMap(Map<String, dynamic> map) {
    return ProductModel(
      id:           (map['id']           as String?) ?? '',
      title:        (map['title']        as String?) ?? '',
      description:  (map['description']  as String?) ?? '',
      category: ProductCategory.values.firstWhere(
        (c) => c.name == map['category'],
        orElse: () => ProductCategory.other,
      ),
      price:        ((map['price'] ?? 0) as num).toDouble(),
      imageUrls:    List<String>.from(map['imageUrls'] ?? []),
      sellerId:     (map['sellerId']     as String?) ?? '',
      sellerName:   (map['sellerName']   as String?) ?? '',
      sellerHostel: (map['sellerHostel'] as String?) ?? '',
      sellerPhone:  (map['sellerPhone']  as String?) ?? '',
      status: ProductStatus.values.firstWhere(
        (s) => s.name == map['status'],
        orElse: () => ProductStatus.available,
      ),
      createdAt: DateTime.parse(
        (map['createdAt'] as String?) ?? DateTime.now().toIso8601String(),
      ),
    );
  }
}
